spring.datasource.url=jdbc:mariadb://20.163.12.107:3306/sumachef
spring.datasource.username=root
spring.datasource.password=loco

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

